cd "D:\GameDev\no-one-lives-forever-2-source\Game"
copy .\built\debug\ClientShellDLL\TO2\CShell.dll "D:\Games\No One Lives Forever 2 - Dev\NewGame\"
copy .\built\debug\ObjectDLL\TO2\Object.lto "D:\Games\No One Lives Forever 2 - Dev\NewGame\"
copy .\built\debug\ClientRes\TO2\CRes.dll "D:\Games\No One Lives Forever 2 - Dev\NewGame\"
echo "Finished!"